TRAIN:
  ENABLE: True #TODO
  DATASET: hockey #TODO
  BATCH_SIZE: 64
  EVAL_PERIOD: 1 #10 #TODO
  CHECKPOINT_PERIOD: 1 #TODO
  AUTO_RESUME: False #Resume training from the latest checkpoint in the output directory. #TODO
  #CHECKPOINT_FILE_PATH: ""   # Path to the checkpoint to load the initial weight. #TODO
  #CHECKPOINT_TYPE: "pytorch" # Checkpoint types include `caffe2` or `pytorch`. #TODO
  #CHECKPOINT_EPOCH_RESET: True # If True, reset epochs when loading checkpoint. #TODO
DATA:
  NUM_FRAMES: 8
  SAMPLING_RATE: 8
  TRAIN_JITTER_SCALES: [256, 320]
  TRAIN_CROP_SIZE: 224
  TEST_CROP_SIZE: 256
  INPUT_CHANNEL_NUM: [3]
  PATH_TO_DATA_DIR: "/home/jovyan/slowfast/data/Hockey" #TODO
  PATH_LABEL_SEPARATOR: "," #TODO
RESNET:
  ZERO_INIT_FINAL_BN: True
  WIDTH_PER_GROUP: 64
  NUM_GROUPS: 1
  DEPTH: 50
  TRANS_FUNC: bottleneck_transform
  STRIDE_1X1: False
  NUM_BLOCK_TEMP_KERNEL: [[3], [4], [6], [3]]
NONLOCAL:
  LOCATION: [[[]], [[]], [[]], [[]]]
  GROUP: [[1], [1], [1], [1]]
  INSTANTIATION: softmax
BN:
  USE_PRECISE_STATS: True
  NUM_BATCHES_PRECISE: 200
SOLVER:
  BASE_LR: 0.1
  LR_POLICY: cosine
  MAX_EPOCH: 10 #196 #TODO
  MOMENTUM: 0.9
  WEIGHT_DECAY: 1e-4
  WARMUP_EPOCHS: 34.0
  WARMUP_START_LR: 0.01
  OPTIMIZING_METHOD: sgd
MODEL:
  NUM_CLASSES: 2 #TODO
  ARCH: i3d
  MODEL_NAME: ResNet
  LOSS_FUNC: cross_entropy
  DROPOUT_RATE: 0.5
TEST:
  ENABLE: False #TODO
  DATASET: hockey #TODO
  BATCH_SIZE: 64
DATA_LOADER:
  NUM_WORKERS: 8
  PIN_MEMORY: True
NUM_GPUS: 1 #8 #TODO
NUM_SHARDS: 1
RNG_SEED: 0
OUTPUT_DIR: .
LOG_MODEL_INFO: True #TODO
#TENSORBOARD: ??